import json
import os
from pathlib import Path

TRAINING_DATA = {
    "consumer": [
        "I bought a product online and it arrived defective. I want a refund.",
        "The quality of the food delivery was very poor and I got food poisoning.",
        "My phone stopped working within one week of purchase. The warranty should cover this.",
        "The e-commerce website charged me twice for the same order.",
        "The product advertised online is not what I received in the box.",
        "My hotel reservation was cancelled without notice and I lost my money.",
        "The customer service refuses to acknowledge my complaint about the faulty appliance.",
        "I ordered electronics and received a damaged item. They won't give me a replacement.",
        "The online seller sold me a counterfeit product.",
        "The product expiry date was not mentioned correctly in the advertisement.",
        "I was charged more than the MRP printed on the packaging.",
        "The washing machine I purchased has a manufacturing defect.",
        "The seller refuses to refund my money for a cancelled order.",
        "I received a completely different brand of laptop than what I ordered.",
        "The airline refused to refund my ticket after they cancelled the flight.",
        "This online shopping website is refusing to honor the replacement warranty.",
        "I got a severe skin allergy from using a cosmetic product that claimed to be natural.",
        "The service center damaged my television while repairing it and wants me to pay.",
        "The dealer sold me a secondhand car claiming it was brand new.",
        "My online transaction failed but the money was deducted and not refunded.",
        "The smart watch has a broken display right out of the box.",
        "The AC unit stopped cooling after two days and the seller is ignoring me.",
        "I was billed for services on my credit card that I never subscribed to.",
        "The merchant sent expired food packets in my grocery order.",
        "The builder has delayed the possession of my flat by over two years.",
        "I paid for a premium subscription but the features are not working.",
        "The furniture delivered was broken and of cheap quality compared to the showroom.",
        "The shoe store refused to exchange the wrong size they sent.",
        "The courier company lost my package and is refusing compensation.",
        "I received a duplicate bill for my internet broadband service.",
        "The gym refuses to cancel my membership and keeps billing my card.",
        "The refrigerator is making a loud noise and the compressor seems faulty.",
        "I bought a toy that broke instantly and is unsafe for kids.",
        "The travel agency did not provide the 5-star hotel they promised in the tour.",
        "I was sold a expired medicine by the local pharmacy.",
        "The digital camera has dead pixels on the sensor and needs replacement.",
        "The online course did not deliver the modules promised in the syllabus.",
        "The insurance company rejected my claim for car damage without reason.",
        "My luggage was damaged during the flight and the airline ignores my complaint.",
        "The store sold me a dress with holes in it and refuses to take it back.",
        "I was charged hidden fees that were not mentioned during booking.",
        "The food product has insects inside the sealed packet.",
        "The solar panels installed do not generate the power promised by the vendor.",
        "The smart TV screen went black after a software update and the brand won't fix it.",
        "I was delivered a fake perfume instead of the original designer brand.",
        "The billing counter charged me twice for a single pair of jeans.",
        "The water purifier is leaking and the installation was done poorly.",
        "The dealership charged me for insurance but did not issue the policy document.",
        "The dry cleaner ruined my expensive suit and refuses to compensate.",
        "The fitness band doesn't track heart rate as advertised.",
        "The book delivered has half the pages missing.",
        "The online taxi driver charged me double the estimated fare.",
        "The power bank exploded while charging on the first day.",
        "The subscription box contains items that are expired and unusable.",
        "The online doctor consultation platform did not connect me to any doctor.",
        "I was sent a refurbished phone instead of a new one.",
        "The warranty card was missing from the product box.",
        "The ticket booking site charged convenience fees twice.",
        "The product description page had false reviews and incorrect specifications.",
        "The car battery died within three months despite a 3-year warranty.",
        "The retail store refused entry to my service dog.",
        "The shifting charges were increased by the packers and movers at the last minute.",
        "The milk delivered was sour and curdled.",
        "The event tickets were cancelled but no refund has been processed.",
        "The induction cooktop does not turn on.",
        "The headphones have only one side working.",
        "The website support is unresponsive to my refund queries.",
        "The iron box overheated and burnt my clothes on first use.",
        "The microwave oven control panel is not responding.",
        "I received a bill with random extra charges for my stay.",
        "The suitcase zipper broke on the very first trip.",
        "The software license key they sold me is invalid.",
        "The online store closed down after taking my advance payment.",
        "The beauty salon burned my hair during a treatment.",
        "The printer is not picking up paper and jamming constantly."
    ],
    "labour": [
        "My employer has not paid my salary for the last three months.",
        "I was fired without any written notice or compensation.",
        "The company deducted a large amount from my salary without justification.",
        "I was promised a promotion but it never happened and my colleague got it instead.",
        "The company forced me to resign by threatening my job.",
        "My employer is not depositing my provident fund contributions.",
        "The company is forcing me to work 14 hours a day without overtime pay.",
        "I was sexually harassed at work and management did nothing about it.",
        "The company reduced my salary without any agreement from me.",
        "My employment contract was terminated verbally without written documentation.",
        "The HR department is refusing to give me my experience certificate.",
        "I was injured on the job but the company refuses to pay medical bills.",
        "The boss is verbally abusing me and creating a hostile work environment.",
        "I was denied maternity leave by my company.",
        "My employer refuses to pay my gratuity after 6 years of service.",
        "I am not being allowed to take my sick leaves even with a medical certificate.",
        "The company terminated my services because I raised a voice against safety violations.",
        "I did not receive my bonus which was contractually guaranteed.",
        "My boss threatens to cancel my visa/work permit if I don't work extra hours.",
        "The company is withholding my full and final settlement after resignation.",
        "I was demoted without any reason or performance review.",
        "The management is discriminating against me based on my gender.",
        "I was fired for taking a medical leave for surgery.",
        "The factory owner does not provide clean drinking water or basic sanitation.",
        "The company does not pay minimum wage as per government rules.",
        "I was forced to work on national holidays without extra pay.",
        "The company changed my shift to night shift without any prior notice.",
        "The boss is threatening to file a false case against me if I leave the company.",
        "I was suspended without pay without any inquiry panel.",
        "My employer does not give weekly off days and makes me work 7 days a week.",
        "The company did not pay my travel allowance as per contract.",
        "I was fired immediately after disclosing my pregnancy to HR.",
        "The company is refusing to clear my pending incentives.",
        "The supervisor is demanding bribes to approve my leaves.",
        "I was forced to sign a blank paper before joining the company.",
        "The safety gear in the chemical plant is outdated and dangerous.",
        "My employer keeps delaying the monthly salary payment date.",
        "I was forced to work during severe illness.",
        "The company shut down overnight without paying the workers' wages.",
        "My designation was changed to a lower role to cut my pay.",
        "The management refuses to investigate my bullying complaint against the manager.",
        "The company is denying my paternity leave.",
        "I was terminated while on approved sick leave.",
        "The boss is withholding my passport and not letting me leave.",
        "The company does not pay for overtime hours worked on weekends.",
        "I am being paid less than male colleagues for the exact same job.",
        "The employer did not issue a joining letter or contract.",
        "The factory has no fire exits or safety measures.",
        "I was fired for refusing to do illegal work for the company.",
        "The management is forcing employees to opt out of the PF scheme.",
        "The company refuses to pay my encashment of accumulated leaves.",
        "I was lock-out of the office because I demanded my salary.",
        "The supervisor uses abusive language in front of other staff.",
        "The company has not paid the severance package after layoffs.",
        "I was denied a promised raise despite meeting all targets.",
        "The company keeps tracking my personal phone without consent.",
        "I was fired for reporting financial fraud in the accounting team.",
        "The employer is paying salary in cash to avoid taxes.",
        "The office has no heating or cooling making it impossible to work.",
        "I was forced to work during a medical emergency.",
        "The HR is ignoring my complaint about wage theft.",
        "The company demands 3 months' notice but fires employees instantly.",
        "I was forced to resign under duress.",
        "The boss calls me at midnight and threatens to fire me if I don't answer.",
        "The company does not have a POSH committee for sexual harassment.",
        "I was not paid for the training period which was mandatory.",
        "The employer is violating labor laws by employing minors.",
        "The company cut my pay during the probation period without warning.",
        "The manager takes credit for my work and threatens my appraisal.",
        "I was forced to sign a non-compete clause that is illegal.",
        "The company refuses to pay wages during the lockdown period.",
        "I was fired because of my religious beliefs.",
        "The office building is structurally unsafe and has cracks.",
        "My employer has blocked my salary account details.",
        "The company does not allow lunch breaks during an 8-hour shift."
    ],
    "criminal": [
        "Someone stole my bicycle from outside my home.",
        "A person assaulted me outside a market and I have witnesses.",
        "My neighbor is harassing me with constant abusive messages.",
        "Someone cheated me by selling me fake gold claiming it was real.",
        "A person is blackmailing me with private photographs.",
        "I was hit by a car intentionally and have injuries.",
        "My house was burglarized and valuables were stolen.",
        "A person is making false allegations against me in front of people.",
        "Someone hacked my social media account and impersonated me.",
        "A person spread false rumors about me causing reputation damage.",
        "I was robbed at knifepoint near the subway station.",
        "Someone forged my signature on a property document.",
        "A group of people threatened to burn my shop down.",
        "I received a call demanding extortion money or they will kill my son.",
        "My spouse is physically abusing me and locking me in the room.",
        "Someone poisoned my pet dog intentionally.",
        "A man was stalking me on my way back from college.",
        "A shopkeeper is selling banned drugs to teenagers.",
        "Someone stole my wallet on a crowded bus.",
        "I was cheated of money in a Ponzi scheme.",
        "Someone broke the window of my car and stole my laptop.",
        "A gang of youths is throwing stones at my house at night.",
        "A person gave me a fake cheque that bounced and now they are absconding.",
        "Someone tried to snatch my gold chain from my neck.",
        "I was scammed by a fake travel agent who took my passport.",
        "A person is illegally trespassing on my private land.",
        "Someone set fire to my garbage bin near my wooden fence.",
        "A doctor performed surgery without consent and caused damage.",
        "I was drugged at a party and my phone and money were stolen.",
        "Someone kidnapped my cousin and is demanding ransom.",
        "A person is selling pirated copies of my movie online.",
        "A public official demanded a bribe to move my file.",
        "Someone is running an illegal gambling den in our residential area.",
        "I was pickpocketed at the railway platform.",
        "Someone spray-painted abusive words on my front door.",
        "A person hit my father with a stick during a minor dispute.",
        "Someone is selling adulterated milk in our neighborhood.",
        "I was cheated by a builder who took booking amount and disappeared.",
        "A man is showing inappropriate videos to kids in the park.",
        "Someone is smuggling alcohol into dry zones.",
        "A person threatened me with a gun over a parking dispute.",
        "My business partner ran away with all the company cash.",
        "Someone hacked into my computer and locked all files demanding ransom.",
        "I was swindled by a fake investment firm online.",
        "A group of people rioted and damaged public vehicles in our lane.",
        "Someone is illegally cutting down government trees in the forest.",
        "A person is selling counterfeit currency notes.",
        "I was abused verbally with casteist slurs in public.",
        "Someone stole water from my irrigation pipes.",
        "A person is conducting illegal animal fights in their backyard.",
        "Someone snatched my phone while I was walking on the street.",
        "A relative is threatening me to sign over my ancestral property.",
        "My car was stolen from the parking lot last night.",
        "Someone is manufacturing duplicate cosmetics under a big brand name.",
        "I was locked inside a room by my in-laws.",
        "A person is selling toxic toys to children.",
        "Someone broke into our office and stole the server.",
        "I was threatened with dire consequences if I testify in court.",
        "A person is running a fake job racket and taking money.",
        "Someone is selling illegal weapons in the local market.",
        "I was defrauded by an online seller who sent stones instead of a phone.",
        "Someone is calling me from different numbers to threaten me.",
        "A delivery boy stole my package from the doorstep.",
        "A person intentionally damaged my motorcycle by cutting the brakes.",
        "Someone is dumping industrial waste in our drinking water source.",
        "I was cheated by a gold merchant who gave low purity gold.",
        "Someone stole my identification documents from my bag.",
        "A person is running a prostitution ring in the apartment next door.",
        "I was attacked by a neighbor's violent dog and they laughed.",
        "Someone is forging degree certificates for money.",
        "A group of people is raising funds falsely claiming it's for charity.",
        "My shop was looted during the night.",
        "Someone is illegally tapping into my electricity meter.",
        "A person is selling fake anticancer medicines.",
        "I was pushed off a running train by a pickpocket."
    ],
    "rti": [
        "I want to request information about the public works department contract for the new highway.",
        "How much money did the municipality spend on traffic lights this year?",
        "I need copies of the records of vehicles registered in my name.",
        "What are the expenditure details of the local police station?",
        "I want to know about the recruitment process of government employees in our district.",
        "How much salary do government officials receive? I need the breakdown.",
        "I need a copy of the approved budget for the education department.",
        "What are the names and qualifications of all teachers in government schools?",
        "I want to request the audit report of the municipal corporation.",
        "How many RTI requests have been filed in our state and how many were approved?",
        "I want to know the status of my passport application which is delayed for 6 months.",
        "I need information on the funds allocated for the local park development.",
        "What is the daily allowance of the municipal commissioner?",
        "I want to request the land records for survey number 45 in our village.",
        "How many government jobs are currently vacant in the transport department?",
        "I need copies of the birth registry from the municipal office.",
        "What are the rules for setting up a commercial shop in a residential area?",
        "I want to know the number of complaints received against the local water department.",
        "How much money was spent on the Prime Minister's visit to our city?",
        "I need the list of beneficiaries of the government housing scheme in my town.",
        "What is the status of the sewer repair work in sector 4?",
        "I want to request the list of files processed by the PIO last month.",
        "How many doctors are currently posted in the civil hospital?",
        "I need information about the pollution level reports of the local river.",
        "What is the criteria for getting a below-poverty-line card?",
        "I want to request the minutes of the meeting of the city council.",
        "How much grant was given to the local NGO by the government?",
        "I need the layout maps of the proposed metro station.",
        "What are the safety clearance reports for the new commercial complex?",
        "I want to know the number of fire safety certificates issued this year.",
        "How many government schools have functional toilets for girls?",
        "I need a copy of the contract signed with the waste management company.",
        "What is the procedure to apply for a ration card?",
        "I want to request the details of road repair expenses in my street.",
        "How many corruption cases are pending against municipal officials?",
        "I need information on the subsidy given for solar panel installation.",
        "What is the total revenue collected from toll booths on national highway 8?",
        "I want to know the number of vacant seats in government colleges.",
        "How many trees were cut down for the smart city project?",
        "I need copies of the forest clearance documents for the mining area.",
        "What is the attendance record of the local corporator?",
        "I want to request the details of funds spent on mid-day meals.",
        "How many public toilets are built under the Swachh Bharat mission in our block?",
        "I need the inspection reports of the food safety officer for local restaurants.",
        "What are the guidelines for issuing driving licenses?",
        "I want to know the criteria for allocation of street vendor licenses.",
        "How much compensation was paid to farmers for land acquisition for the airport?",
        "I need a copy of the notification regarding school fee regulation.",
        "What is the budget allocated for free medicine distribution?",
        "I want to request the status of my water connection application.",
        "How many police personnel are deployed for security in our area?",
        "I need information on the drainage project timeline.",
        "What are the qualification requirements for the post of village head?",
        "I want to request the detail of funds utilized for building the government library.",
        "How many streetlights are non-functional in ward 12?",
        "I need copies of the environmental impact assessment for the power plant.",
        "What is the status of the free Wi-Fi project in the city?",
        "I want to know the subsidy details for electric vehicles.",
        "How many parks are maintained by the municipal corporation?",
        "I need the details of the scholarship distribution for minority students.",
        "What is the number of CCTV cameras installed by police in our ward?",
        "I want to request the tender document for garbage collection.",
        "How many cases were resolved by the local consumer court last year?",
        "I need information about the old age pension scheme distribution list.",
        "What is the water testing frequency for municipal supply?",
        "I want to request the list of approved builders in the city.",
        "How much tax was collected from commercial properties in sector 2?",
        "I need copies of the building plans for the government office.",
        "What is the status of the flyover construction at cross road?",
        "I want to know the details of expenditure on advertisements by the state government.",
        "How many primary health centers are operating in our district?",
        "I need the list of equipment purchased for the government hospital ICU.",
        "What is the status of the clean air initiative funds?",
        "I want to request the rules regarding commercial advertisements on roads.",
        "How many children are enrolled in government primary schools in our village?"
    ],
    "rent": [
        "My landlord is trying to evict me without giving proper notice.",
        "The landlord is not doing any maintenance of the house and it is falling apart.",
        "The landlord wants to increase my rent by 50% in one month.",
        "My landlord is refusing to return my security deposit after I moved out.",
        "The landlord locked me out of the house without notice.",
        "I deposited money but the landlord is not giving me the receipt.",
        "The landlord is entering my house without permission to show it to others.",
        "I paid the rent but landlord is claiming I didn't and threatening to throw me out.",
        "The landlord wants me to leave but won't refund my advance payment.",
        "The house has a flood issue but the landlord refuses to fix it.",
        "The tenant is not paying the monthly rent for past 4 months.",
        "My tenant has sublet my apartment to someone else without my permission.",
        "The tenant is using the residential flat for commercial activities.",
        "My tenant is causing damage to the walls and structure of my house.",
        "The tenant refuses to vacate the property even after the lease agreement expired.",
        "The landlord cut off my water and electricity connection over a dispute.",
        "The landlord refuses to sign the rent agreement document.",
        "My tenant is keeping commercial goods in the garage against the rules.",
        "The landlord is demanding cash payment and refusing online bank transfer.",
        "The tenant is creating a public nuisance by hosting loud parties daily.",
        "The landlord refuses to repair the leaking roof which is ruining my furniture.",
        "My tenant changed the locks of the house without informing me.",
        "The landlord is threatening to throw my belongings on the street.",
        "The tenant has abandoned the flat and left with the keys.",
        "The landlord refuses to allow me to install an internet connection.",
        "My landlord demands extra charges for using the elevator and parking.",
        "The rent agreement has expired but the tenant refuses to sign a new one.",
        "The landlord wants me to vacate because I complained about safety issues.",
        "The tenant is running an illegal office from my apartment.",
        "The landlord is refusing to pay the society maintenance charges.",
        "My tenant is threatening me when I ask for the rent.",
        "The landlord did not refund the double deposit I paid.",
        "The tenant has kept a dog when the lease clearly says no pets allowed.",
        "The landlord wants to sell the house and is forcing me to leave in 10 days.",
        "The bathroom pipeline is blocked but the landlord says it's my responsibility.",
        "The tenant is accumulating unpaid electricity and gas bills.",
        "The landlord enters my balcony from the common terrace without notice.",
        "The tenant refuses to let me inspect the property for repairs.",
        "The landlord charges an exorbitant rate for electricity submeter.",
        "The tenant has painted the entire house black without my consent.",
        "The rent agreement was forged by the broker.",
        "The landlord refuses to provide a parking space that was promised.",
        "The tenant is causing structural damage by breaking a partition wall.",
        "The landlord is accusing me falsely of damaging the property.",
        "The tenant did not pay the maintenance fees to the society.",
        "The landlord refuses to fix the broken window glass since winter.",
        "The tenant refuses to show me the rent payment proof.",
        "The landlord wants me to pay for painting the building exterior.",
        "The tenant left the water tap open causing flooding in the lower flat.",
        "The landlord is harassing my guests at the entrance.",
        "The tenant has not paid the society deposit.",
        "The landlord is forcing me to vacate before the lock-in period.",
        "The tenant has modified the balcony structure illegally.",
        "The landlord wants to charge me for repairing an old lift.",
        "The tenant refuses to clear the garbage from the premises.",
        "The landlord is demanding rent in advance for 6 months.",
        "The tenant has parked their commercial truck in the society slot.",
        "The landlord refuses to fix the fire alarm system.",
        "The tenant is running a catering business in the kitchen.",
        "The landlord wants to charge me for routine wear and tear.",
        "The tenant refuses to clean the common garden space.",
        "The landlord is charging a penalty for late rent which is not in the lease.",
        "The tenant has locked the terrace access which is common.",
        "The landlord refuses to replace the rusty water tank.",
        "The tenant is storing gas cylinders in the living room.",
        "The landlord wants to terminate the lease with 2 days notice.",
        "The tenant has changed the main door structure without my permission.",
        "The landlord refuses to pay the property tax and the authority sealed the flat.",
        "The tenant refuses to leave after receiving 3 months legal notice.",
        "The landlord is using abusive language for delay of 1 day in rent.",
        "The tenant has broken the kitchen cabinets.",
        "The landlord refuses to give the keys to the terrace.",
        "The tenant is keeping commercial vehicles in the parking.",
        "The landlord demands extra money for cleaning the septic tank.",
        "The tenant refuses to pay the water bills."
    ],
    "cyber": [
        "My bank account was hacked and money was transferred without my knowledge.",
        "Someone is posting my private photos on social media without consent.",
        "I received a phishing email and someone got access to my email account.",
        "My website was hacked and malicious code was injected.",
        "Someone is selling my personal data online.",
        "A person created a fake profile in my name and is scamming people.",
        "I was sent a threatening message via WhatsApp.",
        "Someone is harassing me through online comments and messages.",
        "My credit card details were stolen from an online shopping website.",
        "A hacker is demanding money in exchange for not releasing my private videos.",
        "I received a fake call from someone pretending to be a bank manager.",
        "Someone got access to my net banking password and OTP.",
        "My company's database was stolen and put up for sale on the dark web.",
        "Someone is sending abusive emails to my office colleagues using my name.",
        "I was scammed in a cryptocurrency investment platform.",
        "My smart home devices were hacked and are operating automatically.",
        "Someone cloned my SIM card and is using my phone number.",
        "I was locked out of my Instagram account and they are demanding a ransom.",
        "My laptop was infected with malware that encrypts all files.",
        "A fake website is collecting user login credentials under a bank name.",
        "Someone is defaming my business through fake online reviews.",
        "I received a message claiming I won a lottery and asking for processing fees.",
        "My router was hacked and DNS settings were changed.",
        "Someone is blackmailing me online by threatening to leak my chat history.",
        "I was defrauded by an online seller who took money and deleted the account.",
        "Someone is stalking me online and tracking my location.",
        "My email was spoofed and sent spam to all my contacts.",
        "A person is using my trademarked logo on their website.",
        "I fell victim to a work from home job scam online.",
        "Someone is posting hate speech using my IP address.",
        "My digital signature certificate was stolen and misused.",
        "I was scammed by a fake loan app that is now harassing my contacts.",
        "Someone is hosting a fake application on the play store using our brand.",
        "My online gaming account with expensive items was hacked.",
        "I was sent a link on WhatsApp that stole all my contacts when clicked.",
        "Someone is DDOS attacking my business website.",
        "My cloud storage was breached and sensitive documents were leaked.",
        "I received a threat of physical harm on my social media inbox.",
        "Someone is using a deepfake video of me to ruin my reputation.",
        "My online wallet was drained using a malicious app.",
        "Someone is cyberstalking my teenage daughter.",
        "I was cheated by a caller claiming to be from the electricity department.",
        "My Wi-Fi network is being used by neighbors without permission.",
        "Someone is selling pirated versions of my software.",
        "I received a fraudulent message about my PAN card being blocked.",
        "Someone hacked my crypto wallet and stole my Ethereum.",
        "I was sent ransomware via a fake invoice attachment.",
        "Someone is running a fake online lottery in our name.",
        "My business email was hacked and payment coordinates were changed.",
        "I was scammed by a caller claiming to update my KYC.",
        "Someone is sharing my phone number on adult sites to harass me.",
        "My phone was hacked after using a public charging station.",
        "Someone is impersonating police officers online to extort money.",
        "I was defrauded in an online auction site.",
        "My company website domain was stolen.",
        "Someone is sending phishing links pretending to be from Netflix.",
        "I was blackmailed after installing a utility application.",
        "My personal blog was hacked and replaced with political messages.",
        "Someone is using my email ID to register on spam websites.",
        "I was cheated by a fake seller on a social media store.",
        "My online database password was leaked in a public forum.",
        "Someone is tracking my browsing history using spyware.",
        "I received a fake message about parcel delivery asking for custom duty.",
        "Someone is abusing me in a multiplayer online game chat.",
        "My digital identity was stolen to open fake bank accounts.",
        "Someone is sending me links to download malicious software.",
        "My credit card was used for online purchases in another country.",
        "Someone hacked the server of our local school.",
        "I was scammed by a fake investment guru on Telegram.",
        "Someone is using my photos to create dating app profiles.",
        "My business transactions are being monitored by a trojan.",
        "I was threatened with a cyberattack if I don't pay a fee.",
        "Someone is selling illegal software keys online.",
        "My smart watch was hacked and location is being shared.",
        "I received a fraudulent link for tax refund."
    ]
}

# Save training data
output_dir = Path("data/training")
output_dir.mkdir(parents=True, exist_ok=True)

training_file = output_dir / "legal_complaints.json"
with open(training_file, "w") as f:
    json.dump(TRAINING_DATA, f, indent=2)

# Print summary
total = sum(len(v) for v in TRAINING_DATA.values())
print(f"[OK] Training data created: {training_file}")
print(f"\nDomain distribution:")
for domain, examples in TRAINING_DATA.items():
    print(f"  - {domain}: {len(examples)} examples")
print(f"\nTotal: {total} training examples")
